export const messages = {
  en: { appTagline: 'A formula notebook for perfumers', privateByDefault: 'Private by default', localOnly: 'Your formulas stay on your device.', footer: 'Everything starts with the fundamentals.', newFormula: '+ New formula', notebook: 'Notebook', data: 'Data', archive: 'Archive', exportJson: 'Export JSON backup', importJson: 'Import JSON', printPdf: 'Print / Save current formula as PDF', noArchive: 'No archived formulas.', restore: 'Restore', deletePermanently: 'Delete permanently', confirmDelete: 'Confirm delete', deleteNow: 'Delete now', duplicate: 'Duplicate as new formula', reset: 'Reset materials', moveArchive: 'Move to Archive', formula: 'Formula', untitled: 'Untitled formula', parts: 'Parts', material: 'Material', cas: 'CAS / Ref.', percent: 'Percent', actions: 'Actions', addMaterial: '+ Add material', total: 'Total', batch: 'Batch', concentrate: 'Concentrate', solvent: 'Solvent', complete: 'Complete', addParts: (n: number) => `Add ${n} more parts.`, reduceParts: (n: number) => `Reduce by ${n} parts.`, notes: 'Notes', labNotes: 'Lab notes…', saving: 'Saving…', savedLocally: 'Saved locally', sessionOnly: 'Session only', mark: 'Mark', strength: 'Strength', solventCarrier: 'Solvent / carrier', removeDilution: 'Remove dilution', resetQuestion: 'Reset all material rows?', resetKeep: 'Formula ID, formula name, and Notes will be kept.', resetAction: 'Reset', cancel: 'Cancel', importQuestion: 'Import backup?', importReplace: 'This will replace the current Accordbook data on this device.', imported: 'Backup imported successfully.', exported: 'Backup exported.', printUnavailable: 'Print is not available in this environment.', importFailed: 'Import failed.', invalidBackup: 'Invalid Accordbook backup file.', formulaId: 'FORMULA ID', date: 'DATE', prefix: 'Formula ID prefix', save: 'Save', english: 'English', korean: '한국어' },
  ko: { appTagline: '조향사를 위한 포뮬러 노트', privateByDefault: 'Private by default', localOnly: '포뮬러는 이 기기에 보관됩니다.', footer: '모든 것은 기본기에서 시작된다.', newFormula: '+ 새 포뮬러', notebook: '노트', data: '데이터', archive: '보관함', exportJson: 'JSON 백업', importJson: 'JSON 가져오기', printPdf: '현재 포뮬러 인쇄 / PDF 저장', noArchive: '보관된 포뮬러가 없습니다.', restore: '복원', deletePermanently: '영구 삭제', confirmDelete: '삭제 확인', deleteNow: '지금 삭제', duplicate: '새 포뮬러로 복제', reset: '원료 초기화', moveArchive: '보관함으로 이동', formula: '포뮬러', untitled: '이름 없는 포뮬러', parts: '파트', material: '원료', cas: 'CAS / 참조', percent: '백분율', actions: '동작', addMaterial: '+ 원료 추가', total: '합계', batch: '배치', concentrate: '농축도', solvent: '용매', complete: '완료', addParts: (n: number) => `${n} parts를 더 추가하세요.`, reduceParts: (n: number) => `${n} parts를 줄이세요.`, notes: '노트', labNotes: '노트 입력…', saving: '저장 중…', savedLocally: '로컬 저장 완료', sessionOnly: '현재 세션만', mark: '표시', strength: '농도', solventCarrier: '용매 / carrier', removeDilution: '희석 제거', resetQuestion: '모든 원료 행을 초기화할까요?', resetKeep: '포뮬러 ID, 포뮬러 이름, 노트는 유지됩니다.', resetAction: '초기화', cancel: '취소', importQuestion: '백업을 가져올까요?', importReplace: '현재 기기의 Accordbook 데이터가 가져온 백업으로 교체됩니다.', imported: '백업을 성공적으로 가져왔습니다.', exported: '백업을 내보냈습니다.', printUnavailable: '이 환경에서는 인쇄를 사용할 수 없습니다.', importFailed: '가져오기에 실패했습니다.', invalidBackup: '올바른 Accordbook 백업 파일이 아닙니다.', formulaId: '포뮬러 ID', date: '날짜', prefix: '포뮬러 ID 접두사', save: '저장', english: 'English', korean: '한국어' },
} as const

export type Language = keyof typeof messages
export type MessageSet = {
  [Key in keyof typeof messages.en]: typeof messages.en[Key] extends (...args: infer Args) => infer Result
    ? (...args: Args) => Result
    : string
} & { interpretation?: string }
