import type { Formula, FormulaMaterial } from '../models/formula'
import type { FormulaFile, FormulaFileMaterial } from '../models/formulaFile'
import { toFormulaFile } from '../models/formulaFile'
import type { AccordbookStorage } from '../storage/storageService'
import { createFormula } from './formulaLifecycle'
import { createProvenance } from './provenance'

export class FormulaFileError extends Error {}
const isObject = (value: unknown): value is Record<string, unknown> => !!value && typeof value === 'object' && !Array.isArray(value)
function normalizeMaterial(value: unknown): FormulaFileMaterial { if (!isObject(value) || (typeof value.parts !== 'number' && value.parts !== '') || typeof value.material !== 'string') throw new FormulaFileError('Invalid formula row.'); if (value.cas !== undefined && typeof value.cas !== 'string') throw new FormulaFileError('Invalid CAS / Ref.'); if (value.marked !== undefined && typeof value.marked !== 'boolean') throw new FormulaFileError('Invalid highlight state.'); if (value.dilution !== undefined && (!isObject(value.dilution) || typeof value.dilution.enabled !== 'boolean' || typeof value.dilution.percent !== 'number' || typeof value.dilution.solvent !== 'string')) throw new FormulaFileError('Invalid dilution.'); return { parts: value.parts, material: value.material, ...(typeof value.cas === 'string' ? { cas: value.cas } : {}), ...(value.marked === true ? { marked: true } : {}), ...(isObject(value.dilution) ? { dilution: { enabled: value.dilution.enabled as boolean, percent: value.dilution.percent as number, solvent: value.dilution.solvent as string } } : {}) } }
export function parseFormulaFile(input: string): FormulaFile { let raw: unknown; try { raw = JSON.parse(input) } catch { throw new FormulaFileError('Invalid Formula JSON.') }; if (!isObject(raw) || raw.type !== 'accordbook-formula' || raw.formatVersion !== 1 || !isObject(raw.formula) || typeof raw.formula.name !== 'string' || typeof raw.formula.notes !== 'string' || !Array.isArray(raw.formula.rows)) throw new FormulaFileError('Unsupported or invalid Formula file.'); return { type: 'accordbook-formula', formatVersion: 1, exportedAt: typeof raw.exportedAt === 'string' ? raw.exportedAt : new Date().toISOString(), formula: { name: raw.formula.name, notes: raw.formula.notes, rows: raw.formula.rows.map(normalizeMaterial) } } }
const safeName = (name: string) => { const value = name.trim().toLowerCase().replace(/[\\/:*?"<>|]+/g, '').replace(/[^\p{L}\p{N}]+/gu, '-').replace(/^-+|-+$/g, ''); return value ? `accordbook-${value}.json` : 'accordbook-formula.json' }
export function downloadFormulaFile(formula: Formula, date = new Date()): void { const file = { ...toFormulaFile(formula), exportedAt: date.toISOString() }; const blob = new Blob([JSON.stringify(file, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = safeName(formula.name); link.click(); URL.revokeObjectURL(url) }
export async function importFormula(storage: AccordbookStorage, file: FormulaFile, prefix: string): Promise<Formula> { const generated = await createFormula(storage, prefix); const imported: Formula = { ...generated, name: file.formula.name, notes: file.formula.notes, rows: file.formula.rows.map((row) => ({ ...row, id: crypto.randomUUID() })) as FormulaMaterial[] }; imported.provenance = await createProvenance(imported, 'imported', { originType: 'imported' }); await storage.formulas.save(imported); return imported }
