import type { GuideDocument } from '../models/guide'

export type GuideDraftEnvelope = { format: 'accordbook-guide-draft'; formatVersion: 1; guideId: string; revision: number; updatedAt: string; basePublishedFingerprint: string; document: GuideDocument }
export type GuideDraftResult = { ok: true; draft?: GuideDraftEnvelope; revision?: number; updatedAt?: string } | { ok: false; code: 'AUTH_FAILED' | 'NO_DRAFT' | 'REVISION_CONFLICT' | 'INVALID_DRAFT' | 'NETWORK_ERROR'; message?: string }
export type GuideDraftClient = { connect(key: string): Promise<boolean>; getDraft(guideId: string): Promise<GuideDraftResult>; saveDraft(guideId: string, expectedRevision: number | null, basePublishedFingerprint: string, document: GuideDocument): Promise<GuideDraftResult>; deleteDraft(guideId: string): Promise<GuideDraftResult> }
const endpoint = (import.meta.env.VITE_GUIDE_DRAFT_ENDPOINT ?? '').trim()
let operatorKey = ''
const json = async (action: string, payload: Record<string, unknown>) => { if (!endpoint || !operatorKey) return { ok: false, code: 'NETWORK_ERROR' as const }; try { const response = await fetch(endpoint, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action, ...payload, operatorKey }) }); const value = await response.json() as GuideDraftResult; return value } catch { return { ok: false, code: 'NETWORK_ERROR' as const } } }
function stable(value: unknown): unknown { if (Array.isArray(value)) return value.map(stable); if (value && typeof value === 'object') return Object.fromEntries(Object.entries(value as Record<string, unknown>).sort(([a], [b]) => a.localeCompare(b)).map(([key, item]) => [key, stable(item)])); return value }
export async function guideFingerprint(document: GuideDocument): Promise<string> { const canonical = JSON.stringify(stable(document)); const bytes = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(canonical)); return [...new Uint8Array(bytes)].map(value => value.toString(16).padStart(2, '0')).join('') }
export const guideDraftClient: GuideDraftClient = { async connect(key) { if (!key.trim()) return false; operatorKey = key; const result = await json('checkAuth', {}); if (!result.ok) operatorKey = ''; return result.ok }, async getDraft(guideId) { return json('getDraft', { guideId }) }, async saveDraft(guideId, expectedRevision, basePublishedFingerprint, document) { return json('saveDraft', { guideId, expectedRevision, basePublishedFingerprint, document }) }, async deleteDraft(guideId) { return json('deleteDraft', { guideId }) } }
export function isGuideDraftEnvelope(value: unknown): value is GuideDraftEnvelope { if (!value || typeof value !== 'object') return false; const item = value as Record<string, unknown>; const revision = item.revision; return item.format === 'accordbook-guide-draft' && item.formatVersion === 1 && typeof item.guideId === 'string' && typeof revision === 'number' && Number.isInteger(revision) && revision >= 1 && typeof item.updatedAt === 'string' && typeof item.basePublishedFingerprint === 'string' && !!item.document && typeof item.document === 'object' }
