import type { Formula, FormulaMaterial } from '../models/formula'
import type { AccordbookBackup, AccordbookBackupData } from '../models/backup'
import type { IfraDataset, IfraMaterial } from '../models/ifra'
import type { NaturalContributionDataset, NaturalContributionEntry } from '../models/naturalContribution'
import type { AccordbookStorage } from '../storage/storageService'

export class BackupImportError extends Error {}
const normalizeNaturalContributionEntry = (value: Partial<NaturalContributionEntry>): NaturalContributionEntry | undefined => { if (typeof value.ncsCas !== 'string' || typeof value.constituentCas !== 'string' || typeof value.percent !== 'number') return undefined; return { ncsCas: value.ncsCas, ncsName: typeof value.ncsName === 'string' ? value.ncsName : '', constituentCas: value.constituentCas, constituentName: typeof value.constituentName === 'string' ? value.constituentName : '', percent: value.percent } }
const normalizeNaturalContributionDataset = (value: unknown): NaturalContributionDataset | undefined => { if (!value || typeof value !== 'object') return undefined; const data = value as { importedAt?: unknown; entries?: unknown }; if (!Array.isArray(data.entries)) return undefined; return { importedAt: typeof data.importedAt === 'string' ? data.importedAt : new Date().toISOString(), entries: (data.entries as unknown[]).filter((item): item is Partial<NaturalContributionEntry> => !!item && typeof item === 'object').map(normalizeNaturalContributionEntry).filter((item): item is NaturalContributionEntry => item !== undefined) } }
const normalizeIfraMaterial = (value: Partial<IfraMaterial>): IfraMaterial => ({ cas: typeof value.cas === 'string' ? value.cas : '', name: typeof value.name === 'string' ? value.name : '', limits: value.limits && typeof value.limits === 'object' ? Object.fromEntries(Object.entries(value.limits).filter((entry): entry is [string, number] => typeof entry[1] === 'number')) : {}, allergen26: typeof value.allergen26 === 'boolean' ? value.allergen26 : undefined, allergen83: typeof value.allergen83 === 'boolean' ? value.allergen83 : undefined, declaredName: typeof value.declaredName === 'string' ? value.declaredName : undefined })
const normalizeIfraDataset = (value: unknown): IfraDataset | undefined => { if (!value || typeof value !== 'object') return undefined; const data = value as { importedAt?: unknown; categoryKeys?: unknown; materials?: unknown }; if (!Array.isArray(data.materials)) return undefined; return { importedAt: typeof data.importedAt === 'string' ? data.importedAt : new Date().toISOString(), categoryKeys: Array.isArray(data.categoryKeys) ? data.categoryKeys.filter((key): key is string => typeof key === 'string') : [], materials: (data.materials as unknown[]).filter((item): item is Partial<IfraMaterial> => !!item && typeof item === 'object').map(normalizeIfraMaterial).filter((item) => item.cas !== '') } }
const normalizeRow = (row: Partial<FormulaMaterial>, index: number): FormulaMaterial => ({ id: typeof row.id === 'string' ? row.id : `imported-row-${index}`, parts: typeof row.parts === 'number' ? row.parts : '', material: typeof row.material === 'string' ? row.material : '', cas: typeof row.cas === 'string' ? row.cas : undefined, marked: row.marked === true, dilution: row.dilution && typeof row.dilution === 'object' ? { enabled: row.dilution.enabled === true, percent: typeof row.dilution.percent === 'number' ? row.dilution.percent : 10, solvent: typeof row.dilution.solvent === 'string' ? row.dilution.solvent : 'ALC' } : undefined })
const normalizeFormula = (value: Partial<Formula>, index: number): Formula => { if (typeof value.id !== 'string' || typeof value.formulaId !== 'string' || typeof value.date !== 'string') throw new BackupImportError('Invalid Formula data.'); return { id: value.id, formulaId: value.formulaId, date: value.date, name: typeof value.name === 'string' ? value.name : '', notes: typeof value.notes === 'string' ? value.notes : '', rows: Array.isArray(value.rows) ? value.rows.map(normalizeRow) : (() => { throw new BackupImportError('Invalid Formula rows.') })(), createdAt: typeof value.createdAt === 'string' ? value.createdAt : new Date().toISOString(), updatedAt: typeof value.updatedAt === 'string' ? value.updatedAt : new Date().toISOString(), ...(typeof value.archivedAt === 'string' ? { archivedAt: value.archivedAt } : {}), ...(typeof value.intendedUsagePercent === 'number' ? { intendedUsagePercent: value.intendedUsagePercent } : {}), ...(value.intendedProductType === 'leave-on' || value.intendedProductType === 'rinse-off' ? { intendedProductType: value.intendedProductType } : {}) } }
export function parseBackup(input: string): AccordbookBackup { let raw: unknown; try { raw = JSON.parse(input) } catch { throw new BackupImportError('Invalid JSON backup file.') }; if (!raw || typeof raw !== 'object') throw new BackupImportError('Invalid Accordbook backup file.'); const value = raw as Partial<AccordbookBackup>; if (value.app !== 'Accordbook' || value.formatVersion !== 1 || !value.data || typeof value.data !== 'object') throw new BackupImportError('Unsupported or invalid backup version.'); const data = value.data as Partial<AccordbookBackupData>; if (!Array.isArray(data.formulas) || !Array.isArray(data.archive) || !data.settings || typeof data.settings !== 'object' || !data.meta || typeof data.meta !== 'object') throw new BackupImportError('Invalid Accordbook backup structure.'); return { app: 'Accordbook', formatVersion: 1, exportedAt: typeof value.exportedAt === 'string' ? value.exportedAt : new Date().toISOString(), data: { settings: { formulaIdPrefix: typeof data.settings.formulaIdPrefix === 'string' ? data.settings.formulaIdPrefix : 'ACC', language: data.settings.language === 'ko' ? 'ko' : 'en' }, formulas: data.formulas.map((item, index) => normalizeFormula(item, index)), archive: data.archive.map((item, index) => normalizeFormula(item, index)), meta: Object.fromEntries(Object.entries(data.meta).filter((entry): entry is [string, number] => typeof entry[1] === 'number')), ...(normalizeIfraDataset(data.ifraMaterials) ? { ifraMaterials: normalizeIfraDataset(data.ifraMaterials) } : {}), ...(normalizeNaturalContributionDataset(data.naturalContributions) ? { naturalContributions: normalizeNaturalContributionDataset(data.naturalContributions) } : {}) } } }
export async function importBackup(storage: AccordbookStorage, backup: AccordbookBackup): Promise<void> { await storage.importData(backup.data) }
