import type { ClaimedSource, Formula, FormulaProvenance, FormulaRevision, RevisionEventType, FingerprintMetadata, ProvenanceCheckpoint } from '../models/formula'

const text = (value: string) => value.trim().replace(/\r\n?/g, '\n')
export function canonicalComposition(formula: Formula): string { const rows = formula.rows.map((row) => ({ material: text(row.material), cas: text(row.cas ?? ''), parts: typeof row.parts === 'number' ? row.parts : null, dilution: row.dilution ? { percent: row.dilution.percent, solvent: text(row.dilution.solvent).toUpperCase() } : null })).sort((a, b) => JSON.stringify(a).localeCompare(JSON.stringify(b))); return JSON.stringify(rows) }
export async function sha256(value: string): Promise<string> { const bytes = new TextEncoder().encode(value); const digest = await crypto.subtle.digest('SHA-256', bytes); return Array.from(new Uint8Array(digest), (byte) => byte.toString(16).padStart(2, '0')).join('') }
export async function contentFingerprint(formula: Formula): Promise<string> { return sha256(canonicalComposition(formula)) }
export const fingerprintMetadata = async (formula: Formula): Promise<FingerprintMetadata> => ({ algorithm: 'SHA-256', canonicalizationVersion: 1, value: await contentFingerprint(formula) })
const uuid = () => crypto.randomUUID()
export async function createProvenance(formula: Formula, eventType: RevisionEventType = 'created', source: ClaimedSource = { originType: 'original' }, lineage?: Pick<FormulaProvenance, 'rootRecordId' | 'parentRecordId' | 'parentFingerprint'>): Promise<FormulaProvenance> { const recordId = uuid(); const fingerprint = await contentFingerprint(formula); const revision = await makeRevision({ recordId, revisionId: uuid(), sequence: 1, eventType, recordedAt: new Date().toISOString(), contentFingerprint: fingerprint, previousRevisionHash: null }); const provenance: FormulaProvenance = { schemaVersion: 1, recordId, rootRecordId: lineage?.rootRecordId ?? recordId, parentRecordId: lineage?.parentRecordId ?? null, parentFingerprint: lineage?.parentFingerprint ?? null, claimedSource: source, revisions: [revision], currentFingerprint: fingerprint, currentRevisionHash: revision.revisionHash }; provenance.checkpoint = await checkpointFor(formula, 'genesis'); return provenance }
export const checkpointFor = async (formula: Formula, kind: ProvenanceCheckpoint['kind']): Promise<ProvenanceCheckpoint> => ({ kind, recordedAt: new Date().toISOString(), formulaSnapshot: canonicalComposition(formula), fingerprint: await fingerprintMetadata(formula) })
async function makeRevision(input: Omit<FormulaRevision, 'revisionHash'> & { recordId: string }): Promise<FormulaRevision> { const { recordId, ...data } = input; return { ...data, revisionHash: await sha256(JSON.stringify({ schemaVersion: 1, recordId, ...data })) } }
export async function appendRevision(formula: Formula, eventType: RevisionEventType, source = formula.provenance?.claimedSource): Promise<Formula> { const provenance = formula.provenance ?? await createProvenance(formula, 'provenance_initialized', { originType: 'unknown' }); const fingerprint = await contentFingerprint(formula); const revision = await makeRevision({ recordId: provenance.recordId, revisionId: uuid(), sequence: provenance.revisions.length + 1, eventType, recordedAt: new Date().toISOString(), contentFingerprint: fingerprint, previousRevisionHash: provenance.currentRevisionHash }); return { ...formula, provenance: { ...provenance, claimedSource: source ?? provenance.claimedSource, revisions: [...provenance.revisions, revision], currentFingerprint: fingerprint, currentRevisionHash: revision.revisionHash } } }
export async function verifyIntegrity(formula: Formula): Promise<'verified' | 'mismatch' | 'unavailable'> { const p = formula.provenance; if (!p || !p.revisions.length) return 'unavailable'; let previous: string | null = null; for (const revision of p.revisions) { if (revision.previousRevisionHash !== previous) return 'mismatch'; const expected = await sha256(JSON.stringify({ schemaVersion: 1, recordId: p.recordId, revisionId: revision.revisionId, sequence: revision.sequence, eventType: revision.eventType, recordedAt: revision.recordedAt, contentFingerprint: revision.contentFingerprint, previousRevisionHash: revision.previousRevisionHash })); if (expected !== revision.revisionHash) return 'mismatch'; previous = revision.revisionHash } return previous === p.currentRevisionHash && previous === p.revisions[p.revisions.length - 1].revisionHash ? 'verified' : 'mismatch' }
