import type { Formula, FormulaSnapshotRow, ReconstructionDelta, ReconstructionCheckpoint } from '../models/formula'
import { contentFingerprint } from './provenance'

export const CHECKPOINT_INTERVAL = 10
export const snapshotOf = (formula: Formula): FormulaSnapshotRow[] => formula.rows.map((row) => ({ rowId: row.rowId ?? row.id, material: row.material, cas: row.cas, parts: row.parts, dilution: row.dilution ? { ...row.dilution } : undefined }))
export function ensureRowIds(formula: Formula): Formula { return { ...formula, rows: formula.rows.map((row) => row.rowId ? row : { ...row, rowId: crypto.randomUUID() }) } }
export function createDelta(before: FormulaSnapshotRow[], after: FormulaSnapshotRow[]): ReconstructionDelta[] { const result: ReconstructionDelta[] = []; const beforeMap = new Map(before.map((row) => [row.rowId, row])); const afterMap = new Map(after.map((row) => [row.rowId, row])); after.forEach((row, index) => { const previous = beforeMap.get(row.rowId); if (!previous) result.push({ type: 'row_added', rowId: row.rowId, index, after: row }); else if (JSON.stringify(previous) !== JSON.stringify(row)) result.push({ type: 'row_updated', rowId: row.rowId, before: previous, after: row }) }); before.forEach((row, index) => { if (!afterMap.has(row.rowId)) result.push({ type: 'row_removed', rowId: row.rowId, index, before: row }) }); return result }
export function applyDelta(snapshot: FormulaSnapshotRow[], deltas: ReconstructionDelta[]): FormulaSnapshotRow[] { const result: FormulaSnapshotRow[] = snapshot.map((row) => ({ ...row, dilution: row.dilution ? { ...row.dilution } : undefined })); for (const delta of deltas) { if (delta.type === 'row_added' && delta.after) result.splice(delta.index ?? result.length, 0, delta.after); if (delta.type === 'row_removed') { const index = result.findIndex((row) => row.rowId === delta.rowId); if (index >= 0) result.splice(index, 1) } if (delta.type === 'row_updated' && delta.after) { const index = result.findIndex((row) => row.rowId === delta.rowId); if (index >= 0) result[index] = delta.after } } return result }
export async function verifySnapshot(snapshot: FormulaSnapshotRow[], expectedFingerprint: string): Promise<boolean> { const formula = { rows: snapshot } as Formula; return await contentFingerprint(formula) === expectedFingerprint }
export type { ReconstructionCheckpoint }
