import { describe, expect, it } from 'vitest'
import { createBackup } from '../src/services/exportJson'
import { BackupImportError, parseBackup, importBackup } from '../src/services/importJson'
import { createStorage } from '../src/storage/storageService'

const data = { settings: { formulaIdPrefix: 'ACC', language: 'en' as const }, formulas: [], archive: [], versions: [], meta: { 'ACC-2608': 17 } }

describe('backup and import', () => {
  it('creates a v2 backup with Time Machine history', async () => { const storage = await createStorage(); await storage.importData(data); const backup = await createBackup(storage); expect(backup.app).toBe('Accordbook'); expect(backup.formatVersion).toBe(2); expect(backup.data.versions).toEqual([]); expect(backup.exportedAt).toBeTruthy(); expect(backup.data.meta['ACC-2608']).toBe(17); expect(JSON.stringify(backup)).toBeTruthy() })
  it('imports v1 backups with an empty history', () => { const parsed = parseBackup(JSON.stringify({ app: 'Accordbook', formatVersion: 1, data: { settings: {}, formulas: [{ id: 'f', formulaId: 'ACC-2608-001', date: '2026-08-28', rows: [] }], archive: [], meta: {} } })); expect(parsed.formatVersion).toBe(2); expect(parsed.data.versions).toEqual([]); expect(parsed.data.formulas[0].name).toBe(''); expect(parsed.data.formulas[0].notes).toBe('') })
  it('round-trips manual and restore-point versions without changing identity', async () => { const storage = await createStorage(); const version = { versionId: 'v1', parentFormulaId: 'f', versionNumber: 1, kind: 'manual' as const, createdAt: '2026-09-03T00:00:00.000Z', note: 'first', sourceCurrentUpdatedAt: '2026-09-03T00:00:00.000Z', snapshot: { name: 'Test', date: '2026-09-03', notes: 'notes', formulaId: 'ACC-001', rows: [{ rowId: 'r1', parts: 50, material: '', cas: undefined }] } }; const formula = { id: 'f', formulaId: 'ACC-001', date: '2026-09-03', name: 'Test', notes: '', rows: [], createdAt: '2026-09-03T00:00:00.000Z', updatedAt: '2026-09-03T00:00:00.000Z' }; await storage.importData({ ...data, formulas: [formula], versions: [version] }); const backup = await createBackup(storage); const parsed = parseBackup(JSON.stringify(backup)); await importBackup(storage, parsed); expect((await storage.versions.get('v1'))?.snapshot.rows[0].parts).toBe(50); expect((await storage.versions.get('v1'))?.versionId).toBe('v1') })
  it('rejects malformed and unsupported backups', () => { expect(() => parseBackup('{')).toThrow(BackupImportError); expect(() => parseBackup(JSON.stringify({ app: 'Accordbook', formatVersion: 2, data: {} }))).toThrow(BackupImportError) })
  it('replaces stores and restores meta sequence', async () => { const storage = await createStorage(); await importBackup(storage, parseBackup(JSON.stringify({ app: 'Accordbook', formatVersion: 1, data })) ); expect((await storage.exportData()).meta['ACC-2608']).toBe(17) })
})
