import { describe, expect, it } from 'vitest'
import { assessLegacyGuideDraftUpgrade, createGuideDraftRequest, createGuideDraftV2, draftFingerprintChanged, getDraftBasePublishedDocument, getPublishedGuide, guideDraftClient, guideFingerprint, isGuideDraftEnvelope, isGuideDraftEnvelopeV1, isGuideDraftEnvelopeV2, retainedRevisionMetadata, saveGuideDraftEnvelope, upgradeLegacyGuideDraftToV2, clearStoredOperatorKey, readStoredOperatorKey } from '../src/services/guideDrafts'
const document = { schemaVersion: 1 as const, guideId: 'time-machine', slug: 'time-machine', order: 3, metadata: { lastUpdated: '2026-09-14' }, locales: { en: { status: 'PUBLISHED' as const, title: 'Time Machine', subtitle: 'Guide', seo: { title: 'Time Machine', description: 'Guide' } } }, blocks: [] }
describe('Guide draft contract', () => {
  it('accepts only the controlled draft envelope shape', () => { expect(isGuideDraftEnvelope({ format: 'accordbook-guide-draft', formatVersion: 1, guideId: 'time-machine', revision: 1, updatedAt: '2026-09-14T00:00:00.000Z', basePublishedFingerprint: 'abc', document })).toBe(true); expect(isGuideDraftEnvelope({ format: 'other', revision: 1 })).toBe(false) })
  it('fingerprints the same document deterministically and changes on content edits', async () => { const first = await guideFingerprint(document); expect(first).toBe(await guideFingerprint(JSON.parse(JSON.stringify(document)))); expect(first).not.toBe(await guideFingerprint({ ...document, metadata: { lastUpdated: 'changed' } })) })
  it('keeps draft history newest-first and retains at most five revisions', () => { const revisions = Array.from({ length: 6 }, (_, index) => ({ revision: index + 1, updatedAt: `2026-09-${String(index + 1).padStart(2, '0')}`, basePublishedFingerprint: 'abc' })); expect(retainedRevisionMetadata(revisions).map(item => item.revision)).toEqual([6, 5, 4, 3, 2]) })
  it('detects a published-source fingerprint change without mutating the draft', () => { const draft = { format: 'accordbook-guide-draft' as const, formatVersion: 1 as const, guideId: 'time-machine', revision: 3, updatedAt: '2026-09-14T00:00:00.000Z', basePublishedFingerprint: 'abc', document }; expect(draftFingerprintChanged(draft, 'abc')).toBe(false); expect(draftFingerprintChanged(draft, 'def')).toBe(true); expect(draft.basePublishedFingerprint).toBe('abc') })
  it('supports v1/v2 narrowing and never fabricates a v1 base', () => { const v1 = { format: 'accordbook-guide-draft' as const, formatVersion: 1 as const, guideId: 'time-machine', revision: 1, updatedAt: '2026-09-14T00:00:00.000Z', basePublishedFingerprint: 'abc', document }; const v2 = { ...v1, formatVersion: 2 as const, basePublishedDocument: document }; expect(isGuideDraftEnvelope(v1)).toBe(true); expect(isGuideDraftEnvelopeV1(v1)).toBe(true); expect(isGuideDraftEnvelopeV2(v1)).toBe(false); expect(isGuideDraftEnvelope(v2)).toBe(true); expect(isGuideDraftEnvelopeV1(v2)).toBe(false); expect(isGuideDraftEnvelopeV2(v2)).toBe(true); expect(getDraftBasePublishedDocument(v1)).toBeUndefined(); expect(getDraftBasePublishedDocument(v2)).toEqual(document); expect(isGuideDraftEnvelope({ ...v2, basePublishedDocument: undefined })).toBe(false); expect(isGuideDraftEnvelope({ ...v1, formatVersion: 3 })).toBe(false) })
  it('uses a CORS-simple POST and keeps the operator key in the JSON body', () => { const request = createGuideDraftRequest('checkAuth', { guideId: 'time-machine' }, 'fixture-key'); expect(request.method).toBe('POST'); expect(request.headers).toEqual({ 'Content-Type': 'text/plain;charset=UTF-8' }); expect(JSON.parse(request.body as string)).toEqual({ action: 'checkAuth', guideId: 'time-machine', operatorKey: 'fixture-key' }) })
  it('uses sessionStorage helpers and not localStorage', () => { const values = new Map<string, string>(); const storage = { getItem: (key: string) => values.get(key) ?? null, setItem: (key: string, value: string) => values.set(key, value), removeItem: (key: string) => values.delete(key) }; Object.defineProperty(globalThis, 'sessionStorage', { value: storage, configurable: true }); values.set('accordbook.guide.operatorKey', 'fixture-key'); expect(readStoredOperatorKey()).toBe('fixture-key'); clearStoredOperatorKey(); expect(readStoredOperatorKey()).toBe('') })
  it('validates the authoritative published Guide response before returning it', async () => { const published = { ...document, guideId: 'getting-started', slug: 'getting-started' }; const fetcher = async (_input: RequestInfo | URL, init?: RequestInit) => { const action = JSON.parse(String(init?.body)).action; const body = action === 'checkAuth' ? { ok: true } : { ok: true, guideId: 'getting-started', document: published, publishedFingerprint: 'a'.repeat(64) }; return { ok: true, json: async () => body } as Response }; const original = globalThis.fetch; globalThis.fetch = fetcher; try { expect(await guideDraftClient.connect('fixture-key')).toBe(true); const result = await getPublishedGuide('getting-started'); expect(result.ok).toBe(true); if (result.ok) expect(result.document?.guideId).toBe('getting-started') } finally { globalThis.fetch = original } })
  it('rejects an invalid authoritative published Guide response', async () => { const original = globalThis.fetch; globalThis.fetch = async () => ({ ok: true, json: async () => ({ ok: true, guideId: 'getting-started', document: {}, publishedFingerprint: 'bad' }) }) as Response; try { const result = await getPublishedGuide('getting-started'); expect(result).toEqual({ ok: false, code: 'INVALID_RESPONSE' }) } finally { globalThis.fetch = original } })
  it('assesses and upgrades only a non-stale V1 draft', () => { const published = { guideId: 'time-machine', document, publishedFingerprint: 'a'.repeat(64) }; const legacy = { format: 'accordbook-guide-draft' as const, formatVersion: 1 as const, guideId: 'time-machine', revision: 2, updatedAt: '2026-09-14T00:00:00.000Z', basePublishedFingerprint: published.publishedFingerprint, document: { ...document, metadata: { lastUpdated: 'local' } } }; expect(assessLegacyGuideDraftUpgrade(legacy, published)).toEqual({ eligible: true, status: 'eligible' }); const upgraded = upgradeLegacyGuideDraftToV2(legacy, published); expect(upgraded.formatVersion).toBe(2); expect(upgraded.basePublishedDocument).toEqual(document); expect(upgraded.document).toEqual(legacy.document); expect(assessLegacyGuideDraftUpgrade({ ...legacy, basePublishedFingerprint: 'b'.repeat(64) }, published).status).toBe('stale-base-unavailable'); expect(assessLegacyGuideDraftUpgrade({ ...legacy, guideId: 'other' }, published).status).toBe('guide-id-mismatch'); expect(assessLegacyGuideDraftUpgrade(upgraded, published).status).toBe('already-v2') })
  it('creates V2 only from a coherent authoritative snapshot and clones documents', () => { const published = { guideId: 'time-machine', document, publishedFingerprint: 'a'.repeat(64) }; const local = { ...document, metadata: { lastUpdated: 'local' } }; const v2 = createGuideDraftV2({ document: local, published }); expect(v2.formatVersion).toBe(2); expect(v2.guideId).toBe('time-machine'); expect(v2.basePublishedFingerprint).toBe(published.publishedFingerprint); expect(v2.basePublishedDocument).toEqual(document); expect(v2.document).toEqual(local); expect(v2.basePublishedDocument).not.toBe(document) })
  it('preserves V2 fields when using the optional envelope save capability', async () => { const published = { guideId: 'time-machine', document, publishedFingerprint: 'a'.repeat(64) }; const envelope = createGuideDraftV2({ document, published }); const original = globalThis.fetch; let sent: Record<string, unknown> | undefined; globalThis.fetch = (async (_input: RequestInfo | URL, init?: RequestInit) => { sent = JSON.parse(String(init?.body)); return { ok: true, json: async () => ({ ok: true, draft: envelope }) } }) as typeof fetch; try { await guideDraftClient.connect('fixture-key'); await saveGuideDraftEnvelope('time-machine', null, envelope); expect(sent?.formatVersion).toBe(2); expect(sent?.basePublishedDocument).toEqual(document) } finally { globalThis.fetch = original } })
})
