import { describe, expect, it } from 'vitest'
import type { GuideDocument } from '../src/models/guide'
import { mergeGuideDocuments } from '../src/services/guideThreeWayMerge'

const block = (id: string, text: string, src = 'assets/time-machine/en/desktop/a.png') => ({ blockId: id, type: 'step' as const, step: Number(id.slice(1)), content: { en: { text } }, media: { figureId: `${id}-figure`, variants: { en: { desktop: { src, alt: 'alt', caption: 'caption', viewport: 'desktop' } } } } })
const doc = (blocks = [block('a1', 'A'), block('a2', 'B'), block('a3', 'C')], title = 'Title'): GuideDocument => ({ schemaVersion: 1, guideId: 'time-machine', slug: 'time-machine', order: 3, metadata: { lastUpdated: '2026-09-15' }, locales: { en: { status: 'PUBLISHED', title, subtitle: 'Guide', seo: { title, description: 'Description' } } }, blocks })
const merge = (base: GuideDocument, local: GuideDocument, remote: GuideDocument) => mergeGuideDocuments({ base, local, remote })

describe('pure Guide three-way merge', () => {
  it('returns identical documents without conflicts', () => { const a = doc(); expect(merge(a, a, a)).toEqual({ document: a, conflicts: [] }) })
  it('merges local and remote changes to different fields', () => { const b = doc(); const l = doc([block('a1', 'Local'), block('a2', 'B'), block('a3', 'C')]); const r = doc([block('a1', 'A'), block('a2', 'Remote'), block('a3', 'C')]); const result = merge(b, l, r); expect(result.conflicts).toHaveLength(0); expect((result.document?.blocks[0] as any).content.en.text).toBe('Local'); expect((result.document?.blocks[1] as any).content.en.text).toBe('Remote') })
  it('reports deterministic top-level conflicts', () => { const b = doc(); const l = doc(undefined, 'Local'); const r = doc(undefined, 'Remote'); const one = merge(b, l, r); const two = merge(b, l, r); expect(one.conflicts).toHaveLength(2); expect(one.conflicts).toEqual(two.conflicts); expect(one.conflicts[0].kind).toBe('field-edit') })
  it('detects delete/edit and preserves one-sided delete', () => { const b = doc(); const l = doc([block('a2', 'B'), block('a3', 'C')]); const edited = [block('a1', 'Remote edit'), block('a2', 'B'), block('a3', 'C')]; const r = doc(edited); expect(merge(b, l, b).conflicts).toHaveLength(0); expect(merge(b, l, r).conflicts[0].kind).toBe('delete-edit') })
  it('preserves one-sided inserts and detects add/add collisions', () => { const b = doc(); const l = doc([...b.blocks, block('a4', 'Local')]); const r = doc([...b.blocks, block('a5', 'Remote')]); expect(merge(b, l, b).document?.blocks.at(-1)?.blockId).toBe('a4'); const collision = merge(b, doc([...b.blocks, block('a4', 'L')]), doc([...b.blocks, block('a4', 'R')])); expect(collision.conflicts.some(c => c.kind === 'add-add')).toBe(true) })
  it('merges image changes and reports image conflicts at field level', () => { const b = doc(); const l = doc([block('a1', 'A', 'assets/time-machine/en/desktop/local.png'), ...b.blocks.slice(1)]); const r = doc([block('a1', 'A', 'assets/time-machine/en/desktop/remote.png'), ...b.blocks.slice(1)]); const result = merge(b, l, r); expect(result.conflicts.some(c => c.fieldPath?.endsWith('.media.variants.en.desktop.src'))).toBe(true) })
  it('handles independent media variant edits', () => { const b = doc(); const l = doc([block('a1', 'A'), ...b.blocks.slice(1)]); (l.blocks[0] as any).media.variants.en.desktop.src = 'assets/time-machine/en/desktop/local.png'; const r = doc([block('a1', 'A'), ...b.blocks.slice(1)]); (r.blocks[0] as any).media.variants.en.mobile = { src: 'assets/time-machine/en/mobile/remote.png', alt: 'alt', caption: 'caption', viewport: 'mobile' }; const result = merge(b, l, r); expect(result.conflicts).toHaveLength(0); expect((result.document?.blocks[0] as any).media.variants.en.desktop.src).toContain('local'); expect((result.document?.blocks[0] as any).media.variants.en.mobile.src).toContain('remote') })
  it('handles one-sided reorder and reports incompatible reorder', () => { const b = doc(); const l = doc([b.blocks[0], b.blocks[2], b.blocks[1]]); expect(merge(b, l, b).document?.blocks.map(x => x.blockId)).toEqual(['a1', 'a3', 'a2']); const r = doc([b.blocks[2], b.blocks[0], b.blocks[1]]); expect(merge(b, l, r).conflicts.some(c => c.kind === 'order')).toBe(true) })
  it('does not mutate inputs and produces stable conflict ordering', () => { const b = doc(); const l = doc(undefined, 'L'); const r = doc(undefined, 'R'); const before = JSON.stringify(b); const first = merge(b, l, r); merge(b, l, r); expect(JSON.stringify(b)).toBe(before); expect(first.conflicts.map(c => c.conflictId)).toEqual([...first.conflicts].map(c => c.conflictId).sort()) })
})
