import { useEffect, useRef, useState } from 'react'
import { createPortal } from 'react-dom'

export default function ActionsHelp({ language }: { language: 'en' | 'ko' }) {
  const [open, setOpen] = useState(false)
  const [position, setPosition] = useState({ top: 0, left: 0 })
  const anchor = useRef<HTMLButtonElement>(null)
  const popover = useRef<HTMLDivElement>(null)
  const ko = language === 'ko'
  useEffect(() => { const close = () => setOpen(false); window.addEventListener('accordbook:close-help', close); return () => window.removeEventListener('accordbook:close-help', close) }, [])
  useEffect(() => { if (!open) return; const place = () => { const rect = anchor.current?.getBoundingClientRect(); if (!rect) return; const panel = popover.current?.getBoundingClientRect(); const width = panel?.width ?? Math.min(300, window.innerWidth - 28); const height = panel?.height ?? 220; const left = Math.min(Math.max(14, rect.right - width), window.innerWidth - width - 14); const below = rect.bottom + 8; const top = below + height <= window.innerHeight - 14 ? below : Math.max(14, rect.top - height - 8); setPosition({ top, left }) }; const frame = window.requestAnimationFrame(place); const outside = (event: MouseEvent) => { const target = event.target as Node; if (!anchor.current?.contains(target) && !popover.current?.contains(target)) setOpen(false) }; const escape = (event: KeyboardEvent) => { if (event.key === 'Escape') setOpen(false) }; document.addEventListener('mousedown', outside); document.addEventListener('keydown', escape); window.addEventListener('resize', place); window.addEventListener('scroll', place, true); return () => { window.cancelAnimationFrame(frame); document.removeEventListener('mousedown', outside); document.removeEventListener('keydown', escape); window.removeEventListener('resize', place); window.removeEventListener('scroll', place, true) } }, [open])
  const items = ko ? [['DIL', '희석 설정', '희석 원료의 농도와 용매를 설정합니다.'], ['▰', '형광펜', '원료 행을 시각적으로 강조합니다.'], ['×', '행 삭제', '해당 원료 행을 삭제합니다.']] : [['DIL', 'Dilution', 'Set concentration and solvent for a diluted material.'], ['▰', 'Highlight', 'Mark a material row for visual emphasis.'], ['×', 'Remove row', 'Remove this material row from the formula.']]
  const toggle = () => { if (!open) window.dispatchEvent(new Event('accordbook:close-origin')); setOpen(!open) }
  return <><button ref={anchor} className="actions-help-trigger" type="button" aria-label={ko ? '포뮬러 도구 설명' : 'Explain formula actions'} aria-expanded={open} onPointerDown={(event) => event.stopPropagation()} onMouseDown={(event) => event.stopPropagation()} onClick={(event) => { event.stopPropagation(); toggle() }}>?</button>{open && createPortal(<div ref={popover} className="actions-help-popover" role="dialog" style={{ top: position.top, left: position.left }}><div className="actions-help-title">{ko ? '포뮬러 도구' : 'FORMULA ACTIONS'}</div>{items.map(([control, title, description]) => <div className="actions-help-item" key={title}><span className={'actions-help-control ' + (control === 'DIL' ? 'dilution' : control === '▰' ? 'marker' : 'remove')}>{control}</span><div><strong>{title}</strong><p>{description}</p></div></div>)}</div>, document.body)}</>
}
