import { useEffect, useState } from 'react'
import { listFormulaDrops, type PublicFormulaDrop } from '../services/formulaDropPublicApi'
import { formatFormulaDropDate } from '../services/formulaDropDate'
import './formulaDropPage.css'
import '../styles/formula-drop.css'
export default function FormulaDropIndexPage() { const [drops, setDrops] = useState<PublicFormulaDrop[]>(); const [error, setError] = useState(false); const load = () => { setError(false); void listFormulaDrops().then(setDrops).catch(() => setError(true)) }; useEffect(() => { document.title = 'Formula Drops — Accordbook'; setMeta('Explore Formula Drops released for study, testing, and adaptation in Accordbook.', '/drop'); load() }, [])
  if (error) return <Shell><State title="Formula Drops couldn't be loaded right now." action={<button className="formula-drop-button" onClick={load}>RETRY</button>} /></Shell>
  if (!drops) return <Shell><State title="Loading Formula Drops…" /></Shell>
  const active = drops.filter(drop => drop.status === 'ACTIVE'); const previous = drops.filter(drop => drop.status === 'EXPIRED'); return <Shell><div className="formula-drop-intro"><span className="formula-drop-kicker">Formula Drops</span><h1>Small formulas,<br />open to study.</h1><p>Small formulas released for study, testing, and adaptation in Accordbook.</p></div>{active.length > 0 && <DropGroup title="Active Drop" drops={active} />}{previous.length > 0 && <DropGroup title="Previous Drops" drops={previous} />}{!active.length && !previous.length && <State title="Formula Drops will appear here when they are released." />}</Shell> }
function DropGroup({ title, drops }: { title: string; drops: PublicFormulaDrop[] }) { return <section><h2 className="formula-drop-section-title">{title}</h2><div className="formula-drop-grid">{drops.map(drop => <a className="formula-drop-card" href={`/drop/${drop.slug}`} key={drop.dropId}><span className="formula-drop-card-number">FORMULA DROP #{drop.slug}</span><h2>{drop.title}</h2>{drop.subtitle && <p>{drop.subtitle}</p>}<span className="formula-drop-meta">{drop.status === 'ACTIVE' ? `Available until ${formatFormulaDropDate(drop.expiresAt)}` : 'This drop has ended'}</span></a>)}</div></section> }
function Shell({ children }: { children: React.ReactNode }) { return <main className="formula-drop-page"><div className="formula-drop-shell"><header className="formula-drop-header"><a className="formula-drop-brand" href="/">Accordbook</a><a className="formula-drop-nav" href="/">Open Accordbook</a></header>{children}</div></main> }
function State({ title, action }: { title: string; action?: React.ReactNode }) { return <div className="formula-drop-state"><h1>{title}</h1><p className="formula-drop-muted">{action}</p></div> }
function setMeta(description: string, canonical: string) { const set = (selector: string, attr: string, value: string) => { let el = document.querySelector<HTMLMetaElement>(selector); if (!el) { el = document.createElement('meta'); el.setAttribute(attr, selector.includes('name=') ? selector.match(/name="([^"]+)/)?.[1] ?? '' : selector.match(/property="([^"]+)/)?.[1] ?? ''); document.head.appendChild(el) }; el.content = value }; set('meta[name="description"]', 'name', description); let link = document.querySelector<HTMLLinkElement>('link[rel="canonical"]'); if (!link) { link = document.createElement('link'); link.rel = 'canonical'; document.head.appendChild(link) }; link.href = `https://accordbook.org${canonical}` }
