import { useEffect, useMemo, useState } from 'react'
import type { Formula, FormulaVersion, FormulaVersionSnapshot } from '../models/formula'
import { compareFormulaSnapshots, compareFormulaToCurrent } from '../services/formulaVersionCompare'

export function FormulaCompareView({ from, to, versions, language }: { from: FormulaVersionSnapshot; to: Formula; versions: FormulaVersion[]; language: 'en' | 'ko' }) {
  const ko = language === 'ko'; const initial = versions.find((version) => version.snapshot === from); const [fromId, setFromId] = useState(initial?.versionId ?? ''); const [toId, setToId] = useState('current'); const [showUnchanged, setShowUnchanged] = useState(false)
  const manual = versions.filter((version) => version.kind === 'manual')
  const fromVersion = manual.find((version) => version.versionId === fromId) ?? versions.find((version) => version.snapshot === from)
  useEffect(() => { document.querySelectorAll<HTMLSelectElement>('.tm-compare-selectors select').forEach((select) => { Array.from(select.options).forEach((option) => { if (option.textContent === 'vnull') option.textContent = ko ? '복원 지점' : 'RESTORE POINT' }) }) }, [ko, fromVersion])
  const comparison = useMemo(() => toId === 'current' ? compareFormulaToCurrent(fromVersion?.snapshot ?? from, to) : compareFormulaSnapshots(fromVersion?.snapshot ?? from, manual.find((version) => version.versionId === toId)?.snapshot ?? from), [fromVersion, from, to, toId])
  return <div className="tm-compare"><div className="tm-compare-selectors"><label>{ko ? '기준' : 'FROM'}<select value={fromVersion?.versionId ?? 'from'} onChange={(event) => setFromId(event.target.value)}><option value="from">{fromVersion ? `v${fromVersion.versionNumber}` : 'VERSION'}</option>{manual.filter((version) => version.versionId !== fromVersion?.versionId).map((version) => <option key={version.versionId} value={version.versionId}>{`v${version.versionNumber}`}</option>)}</select></label><button className="tm-compare-swap" type="button" onClick={() => setToId(toId === 'current' ? (fromVersion?.versionId ?? 'current') : 'current')} aria-label={ko ? '비교 방향 바꾸기' : 'Swap comparison direction'}>⇄</button><label>{ko ? '대상' : 'TO'}<select value={toId} onChange={(event) => setToId(event.target.value)}><option value="current">{ko ? '현재' : 'CURRENT'}</option>{manual.map((version) => <option key={version.versionId} value={version.versionId}>{`v${version.versionNumber}`}</option>)}</select></label></div><p className="tm-compare-summary">{comparison.summary.changed ? `${comparison.summary.changed} ${ko ? '변경' : 'CHANGED'} · ` : ''}{comparison.summary.added ? `${comparison.summary.added} ${ko ? '추가' : 'ADDED'} · ` : ''}{comparison.summary.removed ? `${comparison.summary.removed} ${ko ? '제거' : 'REMOVED'}` : (comparison.summary.changed || comparison.summary.added ? '' : (ko ? '차이 없음' : 'NO CHANGES'))}</p><div className="tm-compare-ledger">{comparison.rows.filter((row) => showUnchanged || row.status !== 'unchanged').map((row) => <div className={`tm-compare-row ${row.status}`} key={row.rowId}><strong>{row.status === 'added' ? '+' : row.status === 'removed' ? '−' : row.status === 'changed' ? '↕' : '·'}</strong><div><b>{(row.toRow?.material || row.fromRow?.material) || <span className="tm-unnamed-material">{ko ? '이름 없는 원료' : 'UNNAMED MATERIAL'}</span>}</b>{(row.partsDelta ?? 0) !== 0 && <span>{row.fromRow?.parts || 0} → {row.toRow?.parts || 0} ({(row.partsDelta ?? 0) > 0 ? '+' : ''}{row.partsDelta})</span>}{row.changes.material && <small>{ko ? '원료명 변경' : 'MATERIAL CHANGED'}</small>}{row.changes.cas && <small>{ko ? 'CAS 변경' : 'CAS CHANGED'}</small>}{row.changes.dilution && <small>{ko ? '희석 변경' : 'DILUTION CHANGED'}</small>}</div></div>)}</div>{comparison.summary.unchanged > 0 && <button className="tm-unchanged-toggle" type="button" onClick={() => setShowUnchanged((value) => !value)}>{comparison.summary.unchanged} {ko ? "개 원료 변경 없음" : "MATERIALS UNCHANGED"} · {showUnchanged ? (ko ? "숨기기" : "HIDE") : (ko ? "보기" : "SHOW")}</button>}{comparison.notesChanged && <div className="tm-compare-notes"><div className="tm-section-label">{ko ? '노트 변경' : 'NOTES CHANGED'}</div><p>{comparison.from.notes}</p><p>{comparison.to.notes}</p></div>}</div>
}

