import { useEffect, useRef, useState, type ReactNode } from 'react'
import { createFormulaDropEvent, sendFormulaDropEvent } from '../services/formulaDropEvents'
import { startFormulaDropDownload } from '../services/formulaDropDownload'
import { getFormulaDrop, type PublicFormulaDrop } from '../services/formulaDropPublicApi'
import './formulaDropPage.css'
import '../styles/formula-drop.css'
const date = (value: string | null) => value ? new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit', timeZoneName: 'short', timeZone: 'Asia/Seoul' }).format(new Date(value)).toUpperCase() : ''
export default function FormulaDropDetailPage({ dropId }: { dropId: string }) {
  const [drop, setDrop] = useState<PublicFormulaDrop | null>(); const [error, setError] = useState(false); const [busy, setBusy] = useState(false); const [download, setDownload] = useState<{ fileName: string; accessName: string; accessLast4: string; accessPin: string }>(); const [downloadError, setDownloadError] = useState(''); const reported = useRef<string | undefined>(undefined); const source = new URLSearchParams(window.location.search).get('source') ?? undefined
  useEffect(() => { void getFormulaDrop(dropId).then(value => { setDrop(value ?? null); if (value) { document.title = `${value.title} — Formula Drop #${value.slug} | Accordbook`; setMeta(value.subtitle || 'Explore this Formula Drop in Accordbook.', `/drop/${value.slug}`); if (reported.current !== value.dropId) { reported.current = value.dropId; void sendFormulaDropEvent(createFormulaDropEvent(value.dropId, 'view', { source, referrer: document.referrer })) } } }).catch(() => setError(true)) }, [dropId])
  const beginDownload = async () => { if (!drop || drop.status !== 'ACTIVE' || busy) return; setBusy(true); setDownloadError(''); try { const result = await startFormulaDropDownload(drop.dropId, { source, referrer: document.referrer }); setDownload({ fileName: result.fileName, accessName: result.accessName, accessLast4: result.accessLast4, accessPin: result.accessPin }) } catch (caught) { setDownloadError(caught instanceof Error && caught.message === 'not_available' ? 'This Formula Drop has ended.' : 'The Formula could not be prepared right now. Please try again.') } finally { setBusy(false) } }
  if (error) return <Shell><State title="Formula Drops couldn't be loaded right now." /></Shell>; if (drop === undefined) return <Shell><State title="Loading Formula Drop…" /></Shell>; if (!drop) return <Shell><State title="This Drop isn't available." action="FORMULA DROP" /></Shell>
  return <Shell><article className="formula-drop-detail"><span className="formula-drop-kicker">Formula Drop #{drop.slug}</span><h1>{drop.title}</h1>{drop.subtitle && <p className="formula-drop-subtitle">{drop.subtitle}</p>}<span className="formula-drop-status">{drop.status === 'ACTIVE' ? `Available until ${date(drop.expiresAt)}` : 'This drop has ended'}</span>{drop.status === 'ACTIVE' && <div className="formula-drop-download"><button className="formula-drop-button formula-drop-download-button" disabled={busy} onClick={() => void beginDownload()}>{busy ? 'PREPARING…' : 'DOWNLOAD FORMULA'}</button>{downloadError && <p className="formula-drop-error" role="alert">{downloadError}</p>}{download && <div className="formula-drop-access"><strong>FORMULA DOWNLOAD STARTED</strong><p>Use these access details when opening the Licensed Formula in Accordbook.</p><dl><dt>NAME</dt><dd>{download.accessName}</dd><dt>LAST 4 DIGITS</dt><dd>{download.accessLast4}</dd><dt>PIN</dt><dd>{download.accessPin}</dd></dl><a className="formula-drop-button" href="/">OPEN ACCORDBOOK</a></div>}</div>}{drop.status === 'EXPIRED' && <p className="formula-drop-muted">This Formula Drop is no longer available for new imports.</p>}{drop.description && <p className="formula-drop-description">{drop.description}</p>}<div className="formula-drop-actions"><a className="formula-drop-button" href="/">OPEN ACCORDBOOK</a><a className="formula-drop-button" href="/drop">BACK TO FORMULA DROPS</a></div></article></Shell>
}
function Shell({ children }: { children: ReactNode }) { return <main className="formula-drop-page"><div className="formula-drop-shell"><header className="formula-drop-header"><a className="formula-drop-brand" href="/">Accordbook</a><a className="formula-drop-nav" href="/">Open Accordbook</a></header>{children}</div></main> }
function State({ title, action }: { title: string; action?: ReactNode }) { return <div className="formula-drop-state"><span className="formula-drop-kicker">{action || 'Formula Drop'}</span><h1>{title}</h1><a className="formula-drop-button" href="/drop">BACK TO FORMULA DROPS</a></div> }
function setMeta(description: string, canonical: string) { let meta = document.querySelector<HTMLMetaElement>('meta[name="description"]'); if (!meta) { meta = document.createElement('meta'); meta.name = 'description'; document.head.appendChild(meta) }; meta.content = description; let link = document.querySelector<HTMLLinkElement>('link[rel="canonical"]'); if (!link) { link = document.createElement('link'); link.rel = 'canonical'; document.head.appendChild(link) }; link.href = `https://accordbook.org${canonical}` }
