import { useEffect, useState, type ReactNode } from 'react'
import { listFormulaDrops, type PublicFormulaDrop } from '../services/formulaDropPublicApi'
import { archiveDrops, mergeArchiveDrops } from '../services/formulaDropArchive'
import { formatFormulaDropDate } from '../services/formulaDropDate'
import './formulaDropPage.css'
import '../styles/formula-drop.css'
export function selectFeaturedDrop(drops: PublicFormulaDrop[]): PublicFormulaDrop | undefined { return drops.find(drop => drop.status === 'ACTIVE') ?? drops[0] }
export default function FormulaDropIndexPage() {
  const [drops, setDrops] = useState<PublicFormulaDrop[]>(); const [error, setError] = useState(false); const [archiveOnly,setArchiveOnly] = useState(false)
  const load = () => { setError(false); setArchiveOnly(false); void listFormulaDrops().then(value=>setDrops(mergeArchiveDrops(value))).catch(() => {const saved=archiveDrops();if(saved.length){setDrops(saved);setArchiveOnly(true)}else setError(true)}) }
  useEffect(() => { document.title = 'Formula Drops — Accordbook'; setMeta('Explore Formula Drops released for study, testing, and adaptation in Accordbook.', '/drop'); load() }, [])
  return <Shell><div className="formula-drop-intro"><span className="formula-drop-kicker">Formula Drops</span><h1>Formulas shared<br />for perfumers.</h1><p>Explore studies, accords and formulas, then continue working with them in Accordbook.</p>{drops && <span className="formula-drop-intro-meta">{drops.length} {drops.length === 1 ? 'PUBLISHED DROP' : 'PUBLISHED DROPS'}</span>}</div>{archiveOnly&&<p role="status">Showing the published archive. Live download availability could not be confirmed.</p>}<section aria-labelledby="latest-drops-heading" aria-busy={!drops && !error}>{error ? <><h2 id="latest-drops-heading" className="formula-drop-section-title">Latest Drops</h2><State title="We couldn't load the Formula Drops." detail="Please try again." action={<button className="formula-drop-link" onClick={load}>RETRY</button>} /></> : !drops ? <><h2 id="latest-drops-heading" className="formula-drop-section-title">Latest Drops</h2><div className="formula-drop-loading-stage" role="status" aria-live="polite"><span className="formula-drop-kicker">Opening the archive</span><p>Loading published Formula Drops…</p><i aria-hidden="true" /></div></> : drops.length === 0 ? <><h2 id="latest-drops-heading" className="formula-drop-section-title">Latest Drops</h2><State title="No Formula Drops yet." detail="New formulas will appear here." /></> : <><FeaturedDrop drop={selectFeaturedDrop(drops)} />{drops.length > 1 && <><h2 id="latest-drops-heading" className="formula-drop-section-title formula-drop-index-heading">Latest Drops</h2><div className="formula-drop-index" aria-label="Formula Drop index">{drops.map(drop => <DropRow drop={drop} key={drop.dropId} />)}</div></>}</>}</section></Shell>
}
function FeaturedDrop({ drop }: { drop: PublicFormulaDrop | undefined }) { if (!drop) return null; return <section className="formula-drop-featured" aria-labelledby="featured-drop-heading"><div className="formula-drop-featured-label"><span>Featured Drop</span><span>No.{drop.slug}</span></div><div className="formula-drop-featured-body"><div><h2 id="featured-drop-heading">{drop.title}</h2>{drop.subtitle && <p>{drop.subtitle}</p>}<Meta drop={drop} /></div><a className="formula-drop-view" href={'/drop/' + drop.slug}>View Formula <span aria-hidden="true">→</span></a></div></section> }
function DropRow({ drop }: { drop: PublicFormulaDrop }) { return <article className="formula-drop-row"><div className="formula-drop-row-number">No.{drop.slug}</div><div className="formula-drop-row-main"><span className="formula-drop-row-status">{drop.status === 'ACTIVE' ? 'Published' : 'Archive'}</span><h3><a href={'/drop/' + drop.slug}>{drop.title}</a></h3>{drop.subtitle && <p>{drop.subtitle}</p>}<Meta drop={drop} /></div><a className="formula-drop-view" href={'/drop/' + drop.slug} aria-label={'View Formula Drop ' + drop.slug + ': ' + drop.title}>View <span aria-hidden="true">→</span></a></article> }
function Meta({ drop }: { drop: PublicFormulaDrop }) { return <span className="formula-drop-meta">{drop.status === 'ACTIVE' && drop.expiresAt ? 'Available until ' + formatFormulaDropDate(drop.expiresAt) : 'Published Formula'}</span> }
function Shell({ children }: { children: ReactNode }) { return <main className="formula-drop-page"><div className="formula-drop-shell"><header className="formula-drop-header"><a className="formula-drop-brand" href="/">Accordbook</a><a className="formula-drop-nav" href="/">Open Accordbook <span aria-hidden="true">→</span></a></header>{children}<footer className="formula-drop-footer"><span>An open-source formula notebook for perfumers.</span><a href="https://accordbook.org">accordbook.org</a></footer></div></main> }
function State({ title, detail, action }: { title: string; detail?: string; action?: ReactNode }) { return <div className="formula-drop-state"><h3>{title}</h3>{detail && <p>{detail}</p>}{action}</div> }
function setMeta(description: string, canonical: string) { let el = document.querySelector<HTMLMetaElement>('meta[name="description"]'); if (!el) { el = document.createElement('meta'); el.name = 'description'; document.head.appendChild(el) }; el.content = description; let link = document.querySelector<HTMLLinkElement>('link[rel="canonical"]'); if (!link) { link = document.createElement('link'); link.rel = 'canonical'; document.head.appendChild(link) }; link.href = 'https://accordbook.org' + canonical }
