import { useRef, useState } from 'react'
import type { MaterialPaletteInput, MaterialPaletteRecord } from '../models/materialPalette'
import { normalizeMaterialName } from '../services/materialIdentity'
import { paletteCasWarning, validatePaletteInput } from '../services/materialPalette'
import type { MaterialPaletteRepository } from '../storage/materialPaletteRepository'
import type { PaletteExcelPreview } from '../services/materialPaletteExcel'
import PaletteDialog from './PaletteDialog'

export function MaterialPaletteForm({ initial, language, onSave, onClose, existing = [], editingId }: { initial?: MaterialPaletteInput; language: 'en' | 'ko'; onSave: (input: MaterialPaletteInput) => Promise<void>; onClose: () => void; existing?: readonly MaterialPaletteRecord[]; editingId?: string }) {
  const ko = language === 'ko', [error, setError] = useState(''), [busy, setBusy] = useState(false), [cas, setCas] = useState(initial?.cas ?? ''), [name, setName] = useState(initial?.materialName ?? '')
  const duplicate = existing.some(item => item.materialId !== editingId && normalizeMaterialName(item.materialName) === normalizeMaterialName(name))
  return <PaletteDialog title={ko ? '원료 정보' : 'Material details'} onClose={() => { if (!busy) onClose() }}><form className="palette-form" onSubmit={async event => {
    event.preventDefault(); if (busy || duplicate) return; const data = new FormData(event.currentTarget); setBusy(true); setError('')
    try { const percent = String(data.get('percent') ?? '').trim(); await onSave(validatePaletteInput({ materialName: String(data.get('name')), alias: String(data.get('alias') ?? ''), cas, notes: String(data.get('notes') ?? ''), dilution: { ...(percent ? { percent: Number(percent) } : {}), solvent: String(data.get('solvent') ?? '') } })); onClose() } catch (failure) { setError(failure instanceof Error ? failure.message : 'Unable to save / 저장하지 못했습니다.') } finally { setBusy(false) }
  }}><label>{ko ? '원료명' : 'Material Name'} *<input name="name" value={name} onChange={event => setName(event.target.value)} required maxLength={200} autoFocus /></label><label>{ko ? '별칭' : 'Alias'}<input name="alias" defaultValue={initial?.alias} maxLength={200} /></label><label>CAS / Ref.<input name="cas" value={cas} onChange={event => setCas(event.target.value)} maxLength={100} /></label>{paletteCasWarning(cas) && <p className="palette-warning">{ko ? 'CAS 형식·검증 숫자를 확인해 주세요. 참조 번호는 그대로 저장할 수 있습니다.' : 'Check the CAS format/checksum. Reference values can be kept as entered.'}</p>}<div className="palette-form-pair"><label>{ko ? '희석 %' : 'Dilution %'}<input name="percent" type="number" min="0.000001" max="100" step="any" defaultValue={initial?.dilution?.percent} /></label><label>{ko ? '용매' : 'Solvent'}<input name="solvent" maxLength={100} defaultValue={initial?.dilution?.solvent} /></label></div><label>{ko ? '노트' : 'Notes'}<textarea name="notes" maxLength={2000} defaultValue={initial?.notes} /></label>{duplicate && <p role="alert">{ko ? '같은 이름의 원료가 이미 있습니다.' : 'A material with this name already exists.'}</p>}{error && <p role="alert">{error}</p>}<div className="palette-actions"><button type="button" className="btn" disabled={busy} onClick={onClose}>{ko ? '취소' : 'Cancel'}</button><button className="btn primary" disabled={busy || duplicate}>{busy ? '…' : ko ? '저장' : 'Save'}</button></div></form></PaletteDialog>
}

export default function MaterialPaletteWorkspace({ records, repository, language, onChanged, onClose, sessionOnly }: { records: MaterialPaletteRecord[]; repository: MaterialPaletteRepository; language: 'en' | 'ko'; onChanged: () => Promise<void>; onClose: () => void; sessionOnly: boolean }) {
  const ko = language === 'ko', [query, setQuery] = useState(''), [editing, setEditing] = useState<MaterialPaletteRecord | 'new'>(), [deleting, setDeleting] = useState<MaterialPaletteRecord>(), [preview, setPreview] = useState<PaletteExcelPreview>(), [error, setError] = useState(''), [busy, setBusy] = useState(false), input = useRef<HTMLInputElement>(null)
  const run = async (action: () => Promise<void>) => { if (busy) return; setBusy(true); setError(''); try { await action() } catch (failure) { setError(failure instanceof Error ? failure.message : 'Unable to complete / 작업에 실패했습니다.') } finally { setBusy(false) } }
  const excel = async (sample: boolean) => { const module = await import('../services/materialPaletteExcel'); module.downloadPaletteExcel(await module.writePaletteExcel(sample ? module.PALETTE_SAMPLE : records), sample) }
  const visible = records.filter(item => normalizeMaterialName([item.materialName, item.alias, item.cas].join(' ')).includes(normalizeMaterialName(query)))
  return <PaletteDialog title="Material Palette" wide onClose={() => { if (!busy) onClose() }}><p className="palette-meta">{records.length} {ko ? '원료' : 'MATERIALS'} · {sessionOnly ? (ko ? '현재 세션에만 저장됩니다.' : 'Stored for this session only.') : (ko ? 'Material Palette는 이 기기에 저장됩니다.' : 'Material Palette stays on this device.')}</p><p className="palette-meta">{ko ? 'Excel은 직접 가져오고 내보내는 파일입니다. 자동 동기화되지 않습니다.' : 'Import and export your Excel file explicitly. It is not automatically synchronized.'}</p><label className="palette-search"><span className="sr-only">{ko ? '원료 검색' : 'Search materials'}</span><input type="search" placeholder={ko ? '원료 검색…' : 'Search materials…'} value={query} onChange={event => setQuery(event.target.value)} /></label><div className="palette-actions"><button className="btn primary" disabled={busy} onClick={() => setEditing('new')}>{ko ? '+ 원료 추가' : '+ Add Material'}</button><button className="btn" disabled={busy} onClick={() => input.current?.click()}>{ko ? 'Excel 열기' : 'Open Excel'}</button><button className="btn" disabled={busy} onClick={() => void run(() => excel(true))}>{ko ? '샘플 Excel' : 'Sample Excel'}</button><button className="btn" disabled={busy} onClick={() => void run(() => excel(false))}>{ko ? 'Excel 내보내기' : 'Export Excel'}</button><input hidden ref={input} type="file" accept=".xlsx" onChange={event => { const file = event.target.files?.[0]; event.target.value = ''; if (!file) return; void run(async () => { if (!/\.xlsx$/i.test(file.name)) throw new Error('XLSX only / XLSX 파일만 지원합니다.'); const module = await import('../services/materialPaletteExcel'); setPreview(await module.readPaletteExcel(await file.arrayBuffer(), await repository.list())) }) }} /></div>{busy && <p role="status">{ko ? '처리 중…' : 'Working…'}</p>}{error && <p role="alert">{error}</p>}
    <div className="palette-list">{visible.map(item => <article className="palette-record" key={item.materialId}><div><strong>{item.materialName}</strong>{item.alias && <span>{ko ? '별칭' : 'Alias'}: {item.alias}</span>}{item.cas && <span>CAS / Ref.: {item.cas}</span>}{item.dilution && <span>{item.dilution.percent !== undefined ? `${item.dilution.percent}%` : ''} {item.dilution.solvent}</span>}{item.notes && <p>{item.notes}</p>}</div><div className="palette-actions"><button className="btn" disabled={busy} onClick={() => setEditing(item)}>{ko ? '수정' : 'Edit'}</button><button className="btn" disabled={busy} onClick={() => setDeleting(item)}>{ko ? '삭제' : 'Delete'}</button></div></article>)}{!visible.length && <p>{ko ? '표시할 원료가 없습니다.' : 'No materials to display.'}</p>}</div>
    {editing && <MaterialPaletteForm existing={records} editingId={editing === 'new' ? undefined : editing.materialId} initial={editing === 'new' ? undefined : editing} language={language} onClose={() => setEditing(undefined)} onSave={async value => { if (editing === 'new') await repository.add(value); else await repository.update(editing.materialId, value); await onChanged() }} />}
    {deleting && <PaletteDialog title={ko ? '원료 삭제' : 'Delete material'} onClose={() => setDeleting(undefined)}><p>{deleting.materialName}</p><div className="palette-actions"><button className="btn" disabled={busy} onClick={() => setDeleting(undefined)}>{ko ? '취소' : 'Cancel'}</button><button className="btn" disabled={busy} onClick={() => void run(async () => { await repository.remove(deleting.materialId); await onChanged(); setDeleting(undefined) })}>{ko ? '삭제 확인' : 'Confirm delete'}</button></div></PaletteDialog>}
    {preview && <PaletteDialog title={ko ? 'Excel 가져오기 미리보기' : 'Excel import preview'} wide onClose={() => { if (!busy) setPreview(undefined) }}><p>ADD NEW ONLY</p><p>{ko ? '전체 / 유효 / 중복 / 경고 / 오류' : 'Total / Valid / Duplicates / Warnings / Errors'}: {preview.totalRows} / {preview.validRows} / {preview.duplicates} / {preview.warnings} / {preview.errors}</p>{preview.unsupportedColumns.length > 0 && <p className="palette-warning">{ko ? '지원되지 않아 무시되는 열' : 'Unsupported columns (ignored)'}: {preview.unsupportedColumns.join(', ')}</p>}<div className="palette-preview-rows">{preview.rows.map(row => <article key={row.rowNumber}><strong>{row.rowNumber}: {row.input?.materialName} — {row.status}</strong>{row.messages.map((message, i) => <p key={i}>{message}</p>)}</article>)}</div>{error && <p role="alert">{error}</p>}<p>{ko ? '중복 항목은 건너뜁니다. 오류가 있으면 파일을 수정한 후 다시 여세요.' : 'Duplicates are skipped. Correct errors in the file, then open it again.'}</p><button className="btn primary" disabled={busy || preview.errors > 0 || !preview.rows.some(row => row.input && !row.duplicate)} onClick={() => void run(async () => { await repository.addAtomic(preview.rows.filter(row => !row.duplicate && row.input).map(row => row.input!)); await onChanged(); setPreview(undefined) })}>{ko ? '새 원료 추가 적용' : 'Apply new materials'}</button></PaletteDialog>}
  </PaletteDialog>
}
