import type { Formula } from '../models/formula'
import { buildMultiVersionMatrix, type MultiVersionState } from '../services/multiVersionSheet'
import { formatDilutionSuffix } from '../services/dilutionDisplay'
import './multiVersionSheet.css'
import WideWorkspaceShell from './WideWorkspaceShell'

export default function MultiVersionSheet({ formula, states, language, onClose }: { formula: Formula; states: MultiVersionState[]; language: 'en' | 'ko'; onClose: () => void }) {
  const t: any = language === 'ko' ? { close: '멀티 버전 시트 닫기', multiVersionSheet: '멀티 버전 시트', multiVersionRotate: '가로 화면으로 회전해주세요.', multiVersionUnsupported: '멀티 버전 시트는 데스크톱과 가로형 태블릿에서 사용할 수 있습니다.', untitled: '제목 없음', material: '원료 이름', total: '합계' } : { close: 'Close Multi-Version Sheet', multiVersionSheet: 'MULTI-VERSION SHEET', multiVersionRotate: 'Rotate your tablet to landscape.', multiVersionUnsupported: 'Multi-Version Sheet is available on desktop and landscape tablets.', untitled: 'Untitled', material: 'MATERIAL NAME', total: 'TOTAL' }
  const matrix = buildMultiVersionMatrix(states)
  const displayStateLabel = (label: string) => label.replace(/^V0+(\d+)$/, 'V$1')
  const unsupported = typeof window !== 'undefined' && window.innerWidth < 768
  const portraitTablet = typeof window !== 'undefined' && window.innerWidth >= 768 && window.innerWidth < 1200 && window.innerHeight > window.innerWidth
  if (unsupported || portraitTablet) return <main className="multi-version-sheet multi-version-sheet--gate" aria-live="polite"><h1>{t.multiVersionSheet}</h1><p>{portraitTablet ? t.multiVersionRotate : t.multiVersionUnsupported}</p><button className="multi-version-sheet__close" type="button" aria-label={t.close} onClick={onClose}>×</button></main>
  return <WideWorkspaceShell className="multi-version-sheet" formulaId={formula.formulaId} formulaName={formula.name||t.untitled} closeLabel={t.close} onClose={onClose}><div className="multi-version-sheet__table-wrap"><table><colgroup><col className="multi-version-sheet__material-column" />{matrix.states.map(state => <col className="multi-version-sheet__state-column" key={state.id} />)}</colgroup><thead><tr><th className="multi-version-sheet__material-header" scope="col">{t.material}</th>{matrix.states.map(state => <th className="multi-version-sheet__state-header" scope="col" key={state.id}>{displayStateLabel(state.label)}</th>)}</tr></thead><tbody>{matrix.rows.map(row => <tr key={row.identity}><th className="multi-version-sheet__material-cell" scope="row"><span className="multi-version-sheet__material-name">{row.material || t.untitled}</span>{formatDilutionSuffix(row.dilution) && <small className="multi-version-sheet__dilution"> {formatDilutionSuffix(row.dilution)}</small>}</th>{row.cells.map((cell, index) => <td className="multi-version-sheet__value-cell" key={`${row.identity}-${index}`}>{cell ? (cell.parts === '' ? '—' : cell.parts) : '—'}</td>)}</tr>)}</tbody><tfoot><tr><th className="multi-version-sheet__material-cell" scope="row">{t.total}</th>{matrix.totals.map((total, index) => <td className="multi-version-sheet__value-cell" key={index}>{total}</td>)}</tr></tfoot></table></div></WideWorkspaceShell>
}
