import { useMemo, useState } from 'react'
import type { FormulaMaterial } from '../models/formula'
import type { MaterialPaletteInput, MaterialPaletteRecord } from '../models/materialPalette'
import { calculatePaletteCoverage, formulaMaterialToPalette, type PaletteCoverageMaterial } from '../services/materialPaletteCoverage'
import type { MaterialPaletteRepository } from '../storage/materialPaletteRepository'
import PaletteDialog from './PaletteDialog'
import { MaterialPaletteForm } from './MaterialPaletteWorkspace'

interface Props { rows: readonly FormulaMaterial[]; records: readonly MaterialPaletteRecord[]; repository: MaterialPaletteRepository; language: 'en' | 'ko'; onChanged: () => Promise<void> }
export default function PaletteCoverage(props: Props) {
  const [open, setOpen] = useState(false), coverage = useMemo(() => calculatePaletteCoverage(props.rows, props.records), [props.rows, props.records]), ko = props.language === 'ko'
  const missingCount = coverage.missingMaterials.length
  const label = <span className="palette-coverage-label">{ko ? '보유' : 'Owned'} <strong>{coverage.matchedMaterials}</strong><span className="palette-coverage-divider" aria-hidden="true"> · </span>{ko ? '미보유' : 'Missing'} <strong>{missingCount}</strong></span>
  const accessibleLabel = ko
    ? `팔레트에 등록된 원료 ${coverage.matchedMaterials}개 / 고유 원료 ${coverage.totalUniqueMaterials}개, 누락 ${missingCount}개. ${missingCount ? '누락 원료 보기.' : '팔레트 상태 보기.'}`
    : `Material Palette: ${coverage.matchedMaterials} of ${coverage.totalUniqueMaterials} unique materials, ${missingCount} missing. ${missingCount ? 'View missing materials.' : 'View Palette status.'}`
  return <><div className="material-status-row"><span className="material-status-count">{ko ? `원료 ${coverage.totalUniqueMaterials}개` : `${coverage.totalUniqueMaterials} MATERIALS`}</span><button type="button" className="palette-coverage" aria-label={accessibleLabel} aria-haspopup="dialog" title={ko ? '팔레트 원료 현황 보기' : 'View material palette details'} onClick={() => setOpen(true)}>{label}<svg className="palette-coverage-chevron" width="12" height="12" viewBox="0 0 12 12" fill="none" aria-hidden="true"><path d="m4.5 3 3 3-3 3" stroke="currentColor" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round" /></svg></button></div>{open && <MissingMaterials {...props} missing={coverage.missingMaterials} onClose={() => setOpen(false)} />}</>
}
function MissingMaterials({ records, missing, repository, language, onChanged, onClose }: Props & { missing: PaletteCoverageMaterial[]; onClose: () => void }) {
  const ko = language === 'ko', [selected, setSelected] = useState<string[]>([]), [reviewed, setReviewed] = useState<Record<string, MaterialPaletteInput>>({}), [editing, setEditing] = useState<PaletteCoverageMaterial>(), [busy, setBusy] = useState(false), [error, setError] = useState('')
  const ready = (item: PaletteCoverageMaterial) => !item.needsReview || !!reviewed[item.key]
  const selectedCount = missing.filter(item => selected.includes(item.key) && ready(item)).length
  return <PaletteDialog title={ko ? '미보유 원료' : 'Missing Materials'} onClose={() => { if (!busy) onClose() }}><div className="palette-missing-toolbar"><p>{ko ? '추가할 원료를 직접 선택해 주세요.' : 'Select the materials you want to add.'}</p>{missing.length > 0 && <button className="btn" disabled={busy} onClick={() => setSelected(missing.filter(ready).map(item => item.key))}>{ko ? '검토 완료 항목 모두 선택' : 'Select all reviewed materials'}</button>}</div><div className="palette-missing-list">{missing.map(item => { const input = reviewed[item.key] ?? item.sources[0]; return <article className="palette-missing" key={item.key}><div className="palette-missing-details"><label><input type="checkbox" disabled={busy || !ready(item)} checked={selected.includes(item.key)} onChange={event => setSelected(values => event.target.checked ? [...values, item.key] : values.filter(value => value !== item.key))} /><strong>{input.materialName}</strong></label>{input.cas && <p>CAS / Ref.: {input.cas}</p>}{input.dilution && <p>{input.dilution.percent}% {input.dilution.solvent}</p>}{item.needsReview && !reviewed[item.key] && <><p className="palette-warning">{ko ? '검토 필요: 서로 다른 CAS·희석 정보 또는 별칭 충돌이 있습니다.' : 'Needs review: conflicting CAS/dilution or ambiguous alias.'}</p><ul>{item.sources.map((source, i) => <li key={i}>{source.cas || '—'} · {source.dilution ? `${source.dilution.percent}% ${source.dilution.solvent ?? ''}` : '—'}</li>)}</ul></>}</div><button className="btn palette-missing-edit" disabled={busy} onClick={() => setEditing(item)}>{ko ? '검토 / 수정' : 'Review / edit'}</button></article> })}{!missing.length && <p>{ko ? '누락 원료가 없습니다.' : 'No missing materials.'}</p>}</div>{error && <p role="alert">{error}</p>}<div className="palette-actions palette-missing-actions"><span className="palette-meta" aria-live="polite">{ko ? `${selectedCount}개 선택` : `${selectedCount} selected`}</span><button className="btn primary" disabled={busy || !selectedCount} onClick={async () => { setBusy(true); setError(''); try { const inputs = missing.filter(item => selected.includes(item.key) && ready(item)).map(item => reviewed[item.key] ?? item.sources[0]); await repository.addFromFormulaAtomic(inputs); await onChanged(); setSelected([]) } catch (failure) { setError(failure instanceof Error ? failure.message : 'Unable to save'); await onChanged() } finally { setBusy(false) } }}>{ko ? '선택 원료를 팔레트에 추가' : 'Add selected to Palette'}</button></div>{editing && <MaterialPaletteForm existing={records} language={language} initial={reviewed[editing.key] ?? { materialName: editing.materialName, ...(editing.needsReview ? {} : editing.sources[0]) }} onClose={() => setEditing(undefined)} onSave={async input => { setReviewed(values => ({ ...values, [editing.key]: input })) }} />}</PaletteDialog>
}
export function PaletteQuickAdd({ row, records, repository, language, onChanged, visible }: Omit<Props, 'rows'> & { row: FormulaMaterial; visible: boolean }) {
  const [editing, setEditing] = useState(false)
  if (!visible && !editing) return null
  const missing = calculatePaletteCoverage([row], records).missingMaterials.length > 0, ko = language === 'ko'
  if ((!missing || !visible) && !editing) return null
  return <><button type="button" className="palette-quick-add" onPointerDown={event => event.preventDefault()} onMouseDown={event => event.preventDefault()} onClick={() => setEditing(true)} onKeyDown={event => { if (event.key === 'Enter') event.preventDefault() }}>{ko ? '+ 팔레트에 추가' : '+ Add to Material Palette'}</button>{editing && <MaterialPaletteForm existing={records} initial={formulaMaterialToPalette(row)} language={language} onClose={() => setEditing(false)} onSave={async input => { try { await repository.addFromFormulaAtomic([input]); await onChanged() } catch (error) { await onChanged(); throw error } }} />}</>
}
