import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
const origin='https://accordbook.org'
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
export function guideSeoState(doc,requestedLocale,siteOrigin=origin){const ko=doc.locales.ko?.status==='PUBLISHED';const published=requestedLocale==='en'?doc.locales.en.status==='PUBLISHED':ko;const renderedLocale=published?requestedLocale:'en';return{requestedLocale,renderedLocale,isFallback:renderedLocale!==requestedLocale,isIndexable:published&&renderedLocale===requestedLocale,canonicalUrl:`${siteOrigin}/guide/${renderedLocale}/${doc.slug}/`,availableHreflangLocales:['en',...(ko?['ko']:[])]}}
function tags(title,description,state){return `<html lang="${state.renderedLocale}"><head><meta charset="UTF-8"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="robots" content="${state.isIndexable?'index, follow':'noindex, follow'}"><link rel="canonical" href="${state.canonicalUrl}">${state.availableHreflangLocales.map(l=>`<link rel="alternate" hreflang="${l}" href="${origin}/guide/${l}/">`).join('')}`}
export async function loadGuideSource(root){let names=[];try{names=(await readdir(join(root,'content/guide'))).filter(n=>n.endsWith('.json')&&n!=='glossary.json')}catch(e){if(e.code==='ENOENT')return[];throw e}const docs=[];for(const n of names){const d=JSON.parse(await readFile(join(root,'content/guide',n),'utf8'));if(d.schemaVersion!==1)throw new Error(`Guide source has unsupported schema: ${n}`);if(d.locales?.en?.status!=='PUBLISHED')continue;docs.push(d)}return docs.sort((a,b)=>a.order-b.order)}
export function guideShell(shell,title,description,state,body=''){const clean=shell.replace(/<meta name="description"[^>]*>|<link rel="canonical"[^>]*>|<title>[\s\S]*?<\/title>/gi,'');return clean.replace(/<html[^>]*>[\s\S]*?<head>/i,tags(title,description,state)).replace(/<body[^>]*>[\s\S]*?<div id="root"><\/div>[\s\S]*?<\/body>/i,`<body><div id="root">${body}</div></body>`)}
export async function generateGuideRoutes(root,shell){const docs=await loadGuideSource(root),out=join(root,'dist/guide');for(const [locale,title,description,indexable] of [['','Accordbook Guide','A practical guide to working with Accordbook.',false],['en','Accordbook Guide','A practical guide to working with Accordbook.',true],['ko','Accordbook 가이드','Accordbook을 사용하는 실무 안내서입니다.',true]]){await mkdir(join(out,locale),{recursive:true});await writeFile(join(out,locale,'index.html'),guideShell(shell,title,description,{renderedLocale:locale||'en',isIndexable:indexable,canonicalUrl:`${origin}/guide/${locale||'en'}/`,availableHreflangLocales:indexable?['en','ko']:[]},'<main><h1>Accordbook Guide</h1><p>A practical guide to working with Accordbook.</p></main>'))}for(const d of docs)for(const l of ['en','ko']){const s=guideSeoState(d,l),c=d.locales[s.renderedLocale];await mkdir(join(out,l,d.slug),{recursive:true});await writeFile(join(out,l,d.slug,'index.html'),guideShell(shell,c.seo.title,c.seo.description,s))}return{documents:docs}}
export function guideSitemapEntries(docs,siteOrigin=origin){return docs.flatMap(d=>['en','ko'].filter(l=>guideSeoState(d,l,siteOrigin).isIndexable).map(l=>`${siteOrigin}/guide/${l}/${d.slug}/`))}
