import { mkdir, readdir, stat, realpath, readFile, copyFile } from 'node:fs/promises'
import { join, relative, resolve, sep } from 'node:path'
const maxBytes = 5 * 1024 * 1024
export function validateGuideAssetPath(src) { return typeof src==='string' && src.startsWith('assets/') && !src.includes('..') && !src.includes('\\') && !src.includes(':') && !src.includes('://') && /\.(png|webp)$/i.test(src) }
export function isContained(root, candidate) { const r=resolve(root), c=resolve(candidate); return c===r || c.startsWith(r+sep) }
function dimensions(buf, ext) { if(ext==='png'){if(buf.length<24||!buf.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]))||buf.toString('ascii',12,16)!=='IHDR')throw Error('invalid PNG header');const w=buf.readUInt32BE(16),h=buf.readUInt32BE(20);if(!w||!h)throw Error('invalid PNG dimensions');return{format:'png',width:w,height:h}} if(buf.length<16||buf.toString('ascii',0,4)!=='RIFF'||buf.toString('ascii',8,12)!=='WEBP')throw Error('invalid WebP header');const chunk=buf.toString('ascii',12,16);if(chunk==='VP8X'){if(buf.length<30)throw Error('truncated WebP VP8X');return{format:'webp',width:1+buf.readUIntLE(24,3),height:1+buf.readUIntLE(27,3)}} if(chunk==='VP8L'){if(buf.length<25||buf[20]!==0x2f)throw Error('invalid WebP VP8L');const bits=buf.readUInt32LE(21);return{format:'webp',width:1+(bits&0x3fff),height:1+((bits>>14)&0x3fff)}} if(chunk==='VP8 '){if(buf.length<30)throw Error('truncated WebP VP8');const w=buf.readUInt16LE(26)&0x3fff,h=buf.readUInt16LE(28)&0x3fff;if(!w||!h)throw Error('invalid WebP dimensions');return{format:'webp',width:w,height:h}} throw Error('unsupported WebP chunk') }
export async function inspectGuideAsset(filePath) { const info=await stat(filePath);if(!info.isFile())throw Error('not a regular file');if(info.size>maxBytes)throw Error(`file size ${info.size} exceeds ${maxBytes}`);const ext=filePath.toLowerCase().endsWith('.png')?'png':filePath.toLowerCase().endsWith('.webp')?'webp':null;if(!ext)throw Error('unsupported image extension');return{...dimensions(await readFile(filePath),ext),size:info.size} }
function references(docs){const out=[];for(const d of docs)for(const b of d.blocks||[]){const media=b.type==='screenshot'?b.media:b.type==='step'?b.media:undefined;if(!media)continue;for(const [locale,devices] of Object.entries(media.variants||{}))for(const [device,v] of Object.entries(devices||{}))if(v?.src)out.push({guideId:d.guideId,blockId:b.blockId,figureId:media.figureId,locale,device,src:v.src})}return out}
export async function validateGuideDocumentAssets(root,docs){const assetRoot=await realpath(resolve(root,'content/guide/assets'));const refs=references(docs);for(const ref of refs){if(!validateGuideAssetPath(ref.src))throw Error(`Guide asset validation failed\nguideId: ${ref.guideId}\nblockId: ${ref.blockId}\nfigureId: ${ref.figureId}\nlocale: ${ref.locale}\ndevice: ${ref.device}\nsrc: ${ref.src}\nreason: unsafe path`);const file=resolve(assetRoot,ref.src.slice('assets/'.length));let actual;try{actual=await realpath(file)}catch{throw Error(`Guide asset validation failed\nguideId: ${ref.guideId}\nblockId: ${ref.blockId}\nfigureId: ${ref.figureId}\nlocale: ${ref.locale}\ndevice: ${ref.device}\nsrc: ${ref.src}\nreason: file not found`)}if(!isContained(assetRoot,actual))throw Error(`Guide asset validation failed\nguideId: ${ref.guideId}\nblockId: ${ref.blockId}\nfigureId: ${ref.figureId}\nreason: realpath escapes asset root`);await inspectGuideAsset(actual)}return refs}
export async function copyGuideAssets(root,docs=[]){const source=await realpath(resolve(root,'content/guide/assets')).catch(()=>null);if(!source)return[];const target=resolve(root,'dist/guide/assets'),copied=[];async function walk(dir){for(const name of await readdir(dir)){const file=join(dir,name),actual=await realpath(file),info=await stat(file);if(!isContained(source,actual)||!isContained(source,file))throw Error('Guide asset validation failed: symlink escapes asset root');if(info.isDirectory())await walk(file);else if(info.isFile()&&/\.(png|webp)$/i.test(name)){await inspectGuideAsset(actual);const out=join(target,relative(source,actual));await mkdir(resolve(out,'..'),{recursive:true});await copyFile(actual,out);copied.push(out)}}}await walk(source);return copied}
export function assetMime(src){return /\.png$/i.test(src)?'image/png':'image/webp'}
