import { useEffect, useState, type ReactNode } from 'react'
import type { GuideBlock, GuideDocument, GuideLocale, GuideMediaVariant } from '../../models/guide'
import { guideAssetPublicUrl, resolveGuideMedia } from '../../services/guideContracts'
import { guideNavigation, loadGuideDocuments } from '../../services/guideContent'
import { resolveGuideRoute } from '../../services/guideRoutes'
import './guide.css'

const docs = loadGuideDocuments()
const labels = { en: { guide: 'GUIDE', intro: 'A practical guide to working with Accordbook.', fallback: 'This page is not yet available in Korean. The English version is shown below.', previous: 'PREVIOUS', next: 'NEXT', home: 'Guide home', notFound: 'Guide chapter not found' }, ko: { guide: '가이드', intro: 'Accordbook을 사용하는 조용한 실무 안내서입니다.', fallback: '이 페이지는 아직 한국어로 제공되지 않습니다. 아래에 영어 버전을 표시합니다.', previous: '이전', next: '다음', home: '가이드 홈', notFound: '가이드 챕터를 찾을 수 없습니다' } }
export default function GuidePage({ pathname = window.location.pathname }: { pathname?: string }) { const route = resolveGuideRoute(pathname); const preferred = localStorage.getItem('accordbook.locale') === 'ko' ? 'ko' : 'en'; const [locale, setLocale] = useState<GuideLocale>(route.kind === 'GUIDE_CHAPTER' || route.kind === 'GUIDE_LOCALE_HOME' ? route.locale : preferred); const doc = route.kind === 'GUIDE_CHAPTER' ? docs.find(item => item.slug === route.slug) : undefined; const renderedLocale: GuideLocale = doc?.locales[locale]?.status === 'PUBLISHED' ? locale : 'en'; useEffect(() => { document.documentElement.lang = renderedLocale; document.title = doc ? `${(doc.locales[renderedLocale] ?? doc.locales.en).title} — Accordbook Guide` : 'Accordbook Guide' }, [doc, renderedLocale]); if (route.kind === 'GUIDE_CHAPTER' && !doc) return <Shell locale={locale}><p className="guide-empty">{labels[locale].notFound}</p></Shell>; if (doc) return <Chapter doc={doc} requestedLocale={locale} renderedLocale={renderedLocale} onLocale={setLocale} />; return <Home locale={locale} onLocale={setLocale} /> }
export function guideLocaleState(doc: GuideDocument, requestedLocale: GuideLocale) { const renderedLocale: GuideLocale = doc.locales[requestedLocale]?.status === 'PUBLISHED' ? requestedLocale : 'en'; return { requestedLocale, renderedLocale, isFallback: requestedLocale !== renderedLocale } }
export function chapterNavigation(slug: string, documents: GuideDocument[] = loadGuideDocuments()) { const live = guideNavigation.filter(([id]) => documents.some(doc => doc.slug === id && doc.locales.en.status === 'PUBLISHED')); const index = live.findIndex(item => item[0] === slug); return { previous: index > 0 ? live[index - 1] : undefined, next: index >= 0 && index < live.length - 1 ? live[index + 1] : undefined } }
function Shell({ children, locale, onLocale }: { children: ReactNode; locale: GuideLocale; onLocale?: (locale: GuideLocale) => void }) { return <main className="guide-page"><header className="guide-header"><a href="/" className="guide-wordmark">Accordbook</a><a href="/guide" className="guide-label">{labels[locale].guide}</a>{onLocale && <div className="guide-language"><button aria-pressed={locale === 'en'} onClick={() => onLocale('en')}>EN</button><button aria-pressed={locale === 'ko'} onClick={() => onLocale('ko')}>한국어</button></div>}</header>{children}</main> }
function Home({ locale, onLocale }: { locale: GuideLocale; onLocale: (locale: GuideLocale) => void }) { return <Shell locale={locale} onLocale={onLocale}><section className="guide-home"><p className="guide-kicker">ACCORD BOOK / GUIDE</p><h1>Accordbook<br />Guide</h1><p className="guide-intro">{labels[locale].intro}</p><div className="guide-rule" /><nav className="guide-index" aria-label="Guide chapters">{guideNavigation.map(([slug, title], i) => <a href={`/guide/${locale}/${slug}`} key={slug}><span>{String(i + 1).padStart(2, '0')}</span><strong>{title}</strong><em>{docs.some(doc => doc.slug === slug && doc.locales.en.status === 'PUBLISHED') ? 'OPEN' : 'COMING SOON'}</em></a>)}</nav></section></Shell> }
function Chapter({ doc, requestedLocale, renderedLocale, onLocale }: { doc: GuideDocument; requestedLocale: GuideLocale; renderedLocale: GuideLocale; onLocale: (locale: GuideLocale) => void }) { const content = doc.locales[renderedLocale] ?? doc.locales.en; const { previous, next } = chapterNavigation(doc.slug); return <Shell locale={requestedLocale} onLocale={onLocale}><article className="guide-chapter"><a href={`/guide/${requestedLocale}`} className="guide-back">← {labels[requestedLocale].home}</a><p className="guide-kicker">{String(doc.order).padStart(2, '0')} / {content.title}</p><h1>{content.title}</h1><p className="guide-subtitle">{content.subtitle}</p>{requestedLocale !== renderedLocale && <p className="guide-fallback" role="status">{labels[requestedLocale].fallback}</p>}<div className="guide-rule" /><GuideRenderer document={doc} locale={renderedLocale} /><nav className="guide-chapter-nav"><a href={previous ? `/guide/${requestedLocale}/${previous[0]}` : `/guide/${requestedLocale}`}><small>{labels[requestedLocale].previous}</small><span>{previous?.[1] ?? labels[requestedLocale].home}</span></a><a href={next ? `/guide/${requestedLocale}/${next[0]}` : `/guide/${requestedLocale}`}><small>{labels[requestedLocale].next}</small><span>{next?.[1] ?? labels[requestedLocale].home}</span></a></nav></article></Shell> }
export function GuideRenderer({ document, locale, deviceOverride, assetResolver }: { document: GuideDocument; locale: GuideLocale; deviceOverride?: 'desktop' | 'tablet' | 'mobile'; assetResolver?: (src: string) => string | undefined }) { return <div className="guide-renderer">{document.blocks.map(block => <GuideBlockRenderer block={block} locale={locale} deviceOverride={deviceOverride} assetResolver={assetResolver} key={block.blockId} />)}</div> }
function text(block: Extract<GuideBlock, { content: unknown }>, locale: GuideLocale) { return block.content[locale]?.text ?? block.content.en?.text ?? '' }
function Figure({ media, locale, deviceOverride, assetResolver }: { media: Extract<GuideBlock, { type: 'screenshot' }>['media']; locale: GuideLocale; deviceOverride?: 'desktop' | 'tablet' | 'mobile'; assetResolver?: (src: string) => string | undefined }) { const resolved = resolveGuideMedia(media, locale, deviceOverride ?? (window.innerWidth < 768 ? 'mobile' : window.innerWidth < 1200 ? 'tablet' : 'desktop')); const variant = resolved?.variant as GuideMediaVariant | undefined; const src = variant && (assetResolver?.(variant.src) ?? guideAssetPublicUrl(variant.src)); if (!variant || !src) return null; return <figure className="guide-figure"><img src={src} alt={variant.alt} /><figcaption><span>{media.figureId}</span>{variant.caption}</figcaption></figure> }
export function GuideBlockRenderer({ block, locale, deviceOverride, assetResolver }: { block: GuideBlock; locale: GuideLocale; deviceOverride?: 'desktop' | 'tablet' | 'mobile'; assetResolver?: (src: string) => string | undefined }) { if (block.type === 'divider') return <hr className="guide-divider" />; if (block.type === 'screenshot') return <Figure media={block.media} locale={locale} deviceOverride={deviceOverride} assetResolver={assetResolver} />; if (block.type === 'heading') return block.level === 2 ? <h2>{text(block, locale)}</h2> : <h3>{text(block, locale)}</h3>; if (block.type === 'paragraph') return <p>{text(block, locale)}</p>; if (block.type === 'step') return <section className="guide-step"><small>STEP {String(block.step).padStart(2, '0')}</small><p>{text(block, locale)}</p>{block.media && <Figure media={block.media} locale={locale} deviceOverride={deviceOverride} assetResolver={assetResolver} />}</section>; if (block.type === 'note' || block.type === 'warning') return <aside className={`guide-callout ${block.type}`}><small>{block.type.toUpperCase()}</small><p>{text(block, locale)}</p></aside>; if (block.type === 'link') return <p className="guide-link"><a href={block.href}>{text(block, locale)}</a></p>; return null }
